const Feature = @import("../features.zig").Feature;
//syllabic,stress,long,consonantal,sonorant,continuant,delayed_release,approximant,tap,trill,nasal,voice,spread_gl,constr_gl,LABIAL,round,labiodental,CORONAL,anterior,distributed,strident,lateral,DORSAL,high,low,front,back,tense
const FeatureTableType = struct { snd: [:0]const u8, ftrTbl: *const [28:0]u8 };

fn getFeature(i: comptime_int) Feature {
    return switch (i) {
        0 => Feature.syllabic,
        1 => Feature.stress,
        2 => Feature.long,
        3 => Feature.consonantal,
        4 => Feature.sonorant,
        5 => Feature.continuant,
        6 => Feature.delayed_release,
        7 => Feature.approximant,
        8 => Feature.tap,
        9 => Feature.trill,
        10 => Feature.nasal,
        11 => Feature.voice,
        12 => Feature.spread_glottis,
        13 => Feature.constricted_glottis,
        14 => Feature.labial,
        15 => Feature.round,
        16 => Feature.labiodental,
        17 => Feature.coronal,
        18 => Feature.anterior,
        19 => Feature.distributed,
        20 => Feature.strident,
        21 => Feature.lateral,
        22 => Feature.dorsal,
        23 => Feature.high,
        24 => Feature.low,
        25 => Feature.front,
        26 => Feature.back,
        27 => Feature.tense,
        else => unreachable,
    };
}
const Ftype = struct { p: u32, m: u32 };

pub fn getPhonemes(ftt: FeatureTableType) Ftype {
    var plusMask: u32 = 0;
    var minusMask: u32 = 0;
    for (ftt.ftrTbl, 0..) |fch, i| {
        const f = getFeature(i);
        switch (fch) {
            '+' => {
                plusMask |= f.mask();
            },
            '-' => {
                minusMask |= f.mask();
            },
            '0' => {},
            else => unreachable,
        }
    }
    return Ftype{ .p = plusMask, .m = minusMask };
}

pub const featureTable = [_]FeatureTableType{
    FeatureTableType{ .snd = "ɒ", .ftrTbl = "+---++0+---+--++--000-+-+-+0" },
    FeatureTableType{ .snd = "ɑ", .ftrTbl = "+---++0+---+------000-+-+-+0" },
    FeatureTableType{ .snd = "ɶ", .ftrTbl = "+---++0+---+--++--000-+-++-0" },
    FeatureTableType{ .snd = "a", .ftrTbl = "+---++0+---+------000-+-+--0" },
    FeatureTableType{ .snd = "æ", .ftrTbl = "+---++0+---+------000-+-++-0" },
    FeatureTableType{ .snd = "ʌ", .ftrTbl = "+---++0+---+------000-+---+-" },
    FeatureTableType{ .snd = "ɔ", .ftrTbl = "+---++0+---+--++--000-+---+-" },
    FeatureTableType{ .snd = "o", .ftrTbl = "+---++0+---+--++--000-+---++" },
    FeatureTableType{ .snd = "ɤ", .ftrTbl = "+---++0+---+------000-+---++" },
    FeatureTableType{ .snd = "ɘ", .ftrTbl = "+---++0+---+------000-+----+" },
    FeatureTableType{ .snd = "œ", .ftrTbl = "+---++0+---+--++--000-+--+--" },
    FeatureTableType{ .snd = "ə", .ftrTbl = "+---++0+---+------000-+-----" },
    FeatureTableType{ .snd = "e", .ftrTbl = "+---++0+---+------000-+--+-+" },
    FeatureTableType{ .snd = "ɞ", .ftrTbl = "+---++0+---+--++--000-+-----" },
    FeatureTableType{ .snd = "ø", .ftrTbl = "+---++0+---+--++--000-+--+-+" },
    FeatureTableType{ .snd = "ɛ", .ftrTbl = "+---++0+---+------000-+--+--" },
    FeatureTableType{ .snd = "ɵ", .ftrTbl = "+---++0+---+--++--000-+----+" },
    FeatureTableType{ .snd = "ɯ", .ftrTbl = "+---++0+---+------000-++--++" },
    FeatureTableType{ .snd = "u", .ftrTbl = "+---++0+---+--++--000-++--++" },
    FeatureTableType{ .snd = "ʊ", .ftrTbl = "+---++0+---+--++--000-++--+-" },
    FeatureTableType{ .snd = "ɨ", .ftrTbl = "+---++0+---+------000-++---+" },
    FeatureTableType{ .snd = "ʉ", .ftrTbl = "+---++0+---+--++--000-++---+" },
    FeatureTableType{ .snd = "y", .ftrTbl = "+---++0+---+--++--000-++-+-+" },
    FeatureTableType{ .snd = "i", .ftrTbl = "+---++0+---+------000-++-+-+" },
    FeatureTableType{ .snd = "ʏ", .ftrTbl = "+---++0+---+--++--000-++-+--" },
    FeatureTableType{ .snd = "ɪ", .ftrTbl = "+---++0+---+------000-++-+--" },
    FeatureTableType{ .snd = "ŋ+", .ftrTbl = "---++-0---++------000-++-+-0" },
    FeatureTableType{ .snd = "ʟ", .ftrTbl = "---+++0+---+------000+++-+-0" },
    FeatureTableType{ .snd = "ɫ", .ftrTbl = "---+++0+---+-----++--++---+0" },
    FeatureTableType{ .snd = "ɴ", .ftrTbl = "---++-0---++------000-+---+0" },
    FeatureTableType{ .snd = "ʀ", .ftrTbl = "---+++0+-+-+------000-+---+0" },
    FeatureTableType{ .snd = "ɲ", .ftrTbl = "---++-0---++-----+-+--++-+-0" },
    FeatureTableType{ .snd = "ʎ", .ftrTbl = "---+++0+---+-----+-+-+++-+-0" },
    FeatureTableType{ .snd = "ŋ", .ftrTbl = "---++-0---++------000-++-000" },
    FeatureTableType{ .snd = "ŋ˗", .ftrTbl = "---++-0---++------000-++--+0" },
    FeatureTableType{ .snd = "ʟ", .ftrTbl = "---+++0+---+------000+++-000" },
    FeatureTableType{ .snd = "ʟ̠", .ftrTbl = "---+++0+---+------000+++--+0" },
    FeatureTableType{ .snd = "ɳ", .ftrTbl = "---++-0---++-----+-----00000" },
    FeatureTableType{ .snd = "ʙ", .ftrTbl = "---+++0+-+-+--+---000--00000" },
    FeatureTableType{ .snd = "ɭ", .ftrTbl = "---+++0+---+-----+---+-00000" },
    FeatureTableType{ .snd = "ɺ", .ftrTbl = "---+++0++--+-----++--+-00000" },
    FeatureTableType{ .snd = "ɻ", .ftrTbl = "---+++0+---+-----+-----00000" },
    FeatureTableType{ .snd = "ɽ", .ftrTbl = "---+++0++--+-----+-----00000" },
    FeatureTableType{ .snd = "r", .ftrTbl = "---+++0+-+-+-----++----00000" },
    FeatureTableType{ .snd = "n", .ftrTbl = "---++-0---++-----++----00000" },
    FeatureTableType{ .snd = "m", .ftrTbl = "---++-0---++--+---000--00000" },
    FeatureTableType{ .snd = "l", .ftrTbl = "---+++0+---+-----++--+-00000" },
    FeatureTableType{ .snd = "ɾ", .ftrTbl = "---+++0++--+-----++----00000" },
    FeatureTableType{ .snd = "ɱ", .ftrTbl = "---++-0---++--+-+-000--00000" },
    FeatureTableType{ .snd = "ʔ", .ftrTbl = "---+---------+----000--00000" },
    FeatureTableType{ .snd = "ɣ+", .ftrTbl = "---+-++----+------000-++-+-0" },
    FeatureTableType{ .snd = "x+", .ftrTbl = "---+-++-----------000-++-+-0" },
    FeatureTableType{ .snd = "k+", .ftrTbl = "---+--------------000-++-+-0" },
    FeatureTableType{ .snd = "ɡ+", .ftrTbl = "---+-------+------000-++-+-0" },
    FeatureTableType{ .snd = "k+͡x+", .ftrTbl = "---+--+-----------000-++-+-0" },
    FeatureTableType{ .snd = "ɡ+͡ɣ+", .ftrTbl = "---+--+----+------000-++-+-0" },
    FeatureTableType{ .snd = "ħ", .ftrTbl = "---+-++-----------000-+-+-+0" },
    FeatureTableType{ .snd = "ʕ", .ftrTbl = "---+-+-----+------000-+-+-+0" },
    FeatureTableType{ .snd = "ʁ", .ftrTbl = "---+-++----+------000-+---+0" },
    FeatureTableType{ .snd = "q", .ftrTbl = "---+--------------000-+---+0" },
    FeatureTableType{ .snd = "χ", .ftrTbl = "---+-++-----------000-+---+0" },
    FeatureTableType{ .snd = "ɢ", .ftrTbl = "---+-------+------000-+---+0" },
    FeatureTableType{ .snd = "ɕ", .ftrTbl = "---+-++----------++++-++-+-0" },
    FeatureTableType{ .snd = "ɉ", .ftrTbl = "---+-------+-----+-+--++-+-0" },
    FeatureTableType{ .snd = "ʝ", .ftrTbl = "---+-++----+-----+-+--++-+-0" },
    FeatureTableType{ .snd = "c", .ftrTbl = "---+-------------+-+--++-+-0" },
    FeatureTableType{ .snd = "ç", .ftrTbl = "---+-++----------+-+--++-+-0" },
    FeatureTableType{ .snd = "d͡ʑ", .ftrTbl = "---+--+----+-----++++-++-+-0" },
    FeatureTableType{ .snd = "t͡ɕ", .ftrTbl = "---+--+----------++++-++-+-0" },
    FeatureTableType{ .snd = "ɣ", .ftrTbl = "---+-++----+------000-++-000" },
    FeatureTableType{ .snd = "ɣ̠", .ftrTbl = "---+-++----+------000-++--+0" },
    FeatureTableType{ .snd = "x", .ftrTbl = "---+-++-----------000-++-000" },
    FeatureTableType{ .snd = "x̠", .ftrTbl = "---+-++-----------000-++--+0" },
    FeatureTableType{ .snd = "k", .ftrTbl = "---+--------------000-++-000" },
    FeatureTableType{ .snd = "k̠", .ftrTbl = "---+--------------000-++--+0" },
    FeatureTableType{ .snd = "ɡ", .ftrTbl = "---+-------+------000-++-000" },
    FeatureTableType{ .snd = "ɡ̠", .ftrTbl = "---+-------+------000-++--+0" },
    FeatureTableType{ .snd = "ʑ", .ftrTbl = "---+-++----+-----++++-++-+-0" },
    FeatureTableType{ .snd = "ʈ", .ftrTbl = "---+-------------+-----00000" },
    FeatureTableType{ .snd = "ɖ", .ftrTbl = "---+-------+-----+-----00000" },
    FeatureTableType{ .snd = "ɬ", .ftrTbl = "---+-++----------++--+-00000" },
    FeatureTableType{ .snd = "ʐ", .ftrTbl = "---+-++----+-----+--+--00000" },
    FeatureTableType{ .snd = "ɸ", .ftrTbl = "---+-++-------+---000--00000" },
    FeatureTableType{ .snd = "ʂ", .ftrTbl = "---+-++----------+--+--00000" },
    FeatureTableType{ .snd = "ʒ", .ftrTbl = "---+-++----+-----+-++--00000" },
    FeatureTableType{ .snd = "z", .ftrTbl = "---+-++----+-----++-+--00000" },
    FeatureTableType{ .snd = "v", .ftrTbl = "---+-++----+--+-+-000--00000" },
    FeatureTableType{ .snd = "t", .ftrTbl = "---+-------------++----00000" },
    FeatureTableType{ .snd = "ʃ", .ftrTbl = "---+-++----------+-++--00000" },
    FeatureTableType{ .snd = "s", .ftrTbl = "---+-++----------++-+--00000" },
    FeatureTableType{ .snd = "p", .ftrTbl = "---+----------+---000--00000" },
    FeatureTableType{ .snd = "f", .ftrTbl = "---+-++-------+-+-000--00000" },
    FeatureTableType{ .snd = "d", .ftrTbl = "---+-------+-----++----00000" },
    FeatureTableType{ .snd = "b", .ftrTbl = "---+-------+--+---000--00000" },
    FeatureTableType{ .snd = "θ", .ftrTbl = "---+-++----------+++---00000" },
    FeatureTableType{ .snd = "ɮ", .ftrTbl = "---+-++----+-----++--+-00000" },
    FeatureTableType{ .snd = "ð", .ftrTbl = "---+-++----+-----+++---00000" },
    FeatureTableType{ .snd = "β", .ftrTbl = "---+-++----+--+---000--00000" },
    FeatureTableType{ .snd = "d͡ʒ", .ftrTbl = "---+--+----+-----+-++--00000" },
    FeatureTableType{ .snd = "d͡z", .ftrTbl = "---+--+----+-----++-+--00000" },
    FeatureTableType{ .snd = "d͡ɮ", .ftrTbl = "---+--+----+-----++--+-00000" },
    FeatureTableType{ .snd = "d̠͡ɮ̠", .ftrTbl = "---+--+----+-----+-+-+-00000" },
    FeatureTableType{ .snd = "t͡ʃ", .ftrTbl = "---+--+----------+-++--00000" },
    FeatureTableType{ .snd = "t̠͡ɬ̠", .ftrTbl = "---+--+----------+-+-+-00000" },
    FeatureTableType{ .snd = "t͡s", .ftrTbl = "---+--+----------++-+--00000" },
    FeatureTableType{ .snd = "t͡ɬ", .ftrTbl = "---+--+----------++--+-00000" },
    FeatureTableType{ .snd = "t̪͡s̪", .ftrTbl = "---+--+----------++++--00000" },
    FeatureTableType{ .snd = "t̪͡ɬ̪", .ftrTbl = "---+--+----------+++-+-00000" },
    FeatureTableType{ .snd = "d̪͡z̪", .ftrTbl = "---+--+----+-----++++--00000" },
    FeatureTableType{ .snd = "d̪͡ɮ̪", .ftrTbl = "---+--+----+-----+++-+-00000" },
    FeatureTableType{ .snd = "ʈ͡ʂ", .ftrTbl = "---+--+----------+--+--00000" },
    FeatureTableType{ .snd = "ɖ͡ʐ", .ftrTbl = "---+--+----+-----+--+--00000" },
    FeatureTableType{ .snd = "p͡f", .ftrTbl = "---+--+-------+-+-000--00000" },
    FeatureTableType{ .snd = "b͡v", .ftrTbl = "---+--+----+--+-+-000--00000" },
    FeatureTableType{ .snd = "p͡ɸ", .ftrTbl = "---+--+-------+---000--00000" },
    FeatureTableType{ .snd = "b͡β", .ftrTbl = "---+--+----+--+---000--00000" },
    FeatureTableType{ .snd = "t̪͡θ", .ftrTbl = "---+--+----------+++---00000" },
    FeatureTableType{ .snd = "d̪͡ð", .ftrTbl = "---+--+----+-----+++---00000" },
    FeatureTableType{ .snd = "c͡ç", .ftrTbl = "---+--+----------+-+--++-+-0" },
    FeatureTableType{ .snd = "ɉ͡ʝ", .ftrTbl = "---+--+----+-----+-+--++-+-0" },
    FeatureTableType{ .snd = "k͡x", .ftrTbl = "---+--+-----------000-++-000" },
    FeatureTableType{ .snd = "k̠͡x̠", .ftrTbl = "---+--+-----------000-++--+0" },
    FeatureTableType{ .snd = "ɡ͡ɣ", .ftrTbl = "---+--+----+------000-++-000" },
    FeatureTableType{ .snd = "ɡ̠̠͡ɣ̠", .ftrTbl = "---+--+----+------000-++--+0" },
    FeatureTableType{ .snd = "q͡χ", .ftrTbl = "---+--+-----------000-+---+0" },
    FeatureTableType{ .snd = "ɢ͡ʁ", .ftrTbl = "---+--+----+------000-+---+0" },
    FeatureTableType{ .snd = "ɧ", .ftrTbl = "---+-++----------+-++-++-000" },
    FeatureTableType{ .snd = "k͡p", .ftrTbl = "---+----------+---000-++-000" },
    FeatureTableType{ .snd = "g͡b", .ftrTbl = "---+-------+--+---000-++-000" },
    FeatureTableType{ .snd = "p͡t", .ftrTbl = "---+----------+--++-+--00000" },
    FeatureTableType{ .snd = "b͡d", .ftrTbl = "---+-------+--+--++-+--00000" },
    FeatureTableType{ .snd = "ɰ", .ftrTbl = "----++0+---+------000-++-00+" },
    FeatureTableType{ .snd = "ɰ̠", .ftrTbl = "----++0+---+------000-++--++" },
    FeatureTableType{ .snd = "w", .ftrTbl = "----++0+---+--++--000-++--++" },
    FeatureTableType{ .snd = "ɥ", .ftrTbl = "----++0+---+--++--000-++-+-+" },
    FeatureTableType{ .snd = "j", .ftrTbl = "----++0+---+------000-++-+-+" },
    FeatureTableType{ .snd = "ɹ", .ftrTbl = "----++0+---+-----+-+---00000" },
    FeatureTableType{ .snd = "ʋ", .ftrTbl = "----++0+---+--+-+-000--00000" },
    FeatureTableType{ .snd = "ʍ", .ftrTbl = "-----++-----+-++--000-++--++" },
    FeatureTableType{ .snd = "ɦ", .ftrTbl = "-----++----++-----000--00000" },
    FeatureTableType{ .snd = "h", .ftrTbl = "-----++-----+-----000--00000" },
};
